# Generated by Django 4.2.9 on 2024-01-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('spot_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
