# Generated by Django 4.2.9 on 2024-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_travelspot_delete_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_spot_images/'),
        ),
    ]
