# Generated by Django 4.2.9 on 2024-01-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_travelspot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
